### ISSUE TITLE
Update on Home Assistant 0.116

### ISSUE THREAD

**Issue by alesoft73** [faeibson/lovelace-multiline-text-input-card#3]
Hi,
in the ultimate release of Home Assistant your custom component don't show..

Many thanks for your great work!

**Comment by faeibson** [comment]
Hi,
I really appreciate that you're using my card. I have noticed the problems caused by lazy loading on the newer releases of Home Assistant with plenty of custom cards and also with this one. Unfortunately I'm not quite sure when, or if, I'll have some time to find out how to solve the problem, since I'm pretty busy at the moment. Sorry!

Regards,
Fabian

**Comment by alesoft73** [comment]
Hi,
don't warry!
I attend....

Thanks another for your job!

**Comment by faeibson** [comment]
Fortunately, the solution was quite easy after I looked up benct's fix :)

**Comment by alesoft73** [comment]
Many thanks.. I send you a 🍻
Give me a link for send a beer please...

**Comment by faeibson** [comment]
No problem, really, but I won't complain either :D
buymeacoff.ee/faeibson

Many thanks! 👍 👍

**Comment by alesoft73** [comment]
Thanks another..
the beer  are for next update😘
